version: "3.9"

services:

  prometheus:
    image: prom/prometheus:main
    #    ports:
    #      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager   # Работает только на главной ноде
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    networks:
      - shared_net

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.53.0
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--docker_only"
    deploy:
      mode: global     # Запустится на всех серверах автоматически
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - shared_net

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      mode: global   # На каждом сервере Swarm — один экземпляр
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    networks:
      - shared_net

  grafana:
    image: grafana/grafana:11.5.2
    #    ports:
    #      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SERVER_ROOT_URL: http://vpn-boriska.ru/grafana
    #      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - shared_net
  nginx:
    image: nginx:latest
    #    ports:
    #      - "80:80"
    #      - "443:443"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - shared_net

volumes:
  grafana_data:
    name: grafana_vol
  prometheus_data:
    name: prometheus_data
  loki_data:
    name: loki_data

networks:
  shared_net:
    external: true
    name: shared_net
