services:

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.60.5
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor=unconfined
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--docker_only"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  node-exporter:
    image: prom/node-exporter:v1.12.1
    container_name: node-exporter
    hostname: vpn-boriska.ru
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  alloy:
    image: grafana/alloy:v1.18.1
    container_name: alloy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    ports:
      - "127.0.0.1:12345:12345"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
