services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_web.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    network_mode: host
#    ports:
#      - "80:80"
#      - "443:443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M

  socks5proxy:
    image: socks5proxy:latest
    container_name: socks5proxy
    environment:
      SOCKS5_LOGIN: "tguser"
      SOCKS5_PASSWORD: "superStrongPass123"
      SOCKS5_PORT: "8888"
    ports:
      - "127.0.0.1:8888:8888"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
#    networks:
#      - shared_net

networks:
  shared_net:
    name: shared_net
    external: true



