services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_web.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
#    ports:
#      - "91.149.219.221:80:80"
#      - "91.149.219.221:443:443"
#      - "94.156.116.218:443:443"
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
#    networks:
#      - shared_net
#
#networks:
#  shared_net:
#    name: shared_net
#    external: true



