version: "3.9"

services:

  prometheus:
    image: prom/prometheus:main
#    ports:
#      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager   # Работает только на главной ноде
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    networks:
      - monitoring_net

  cadvisor:
    image: google/cadvisor:canary
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--docker_only"
    deploy:
      mode: global     # Запустится на всех серверах автоматически
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - monitoring_net

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      mode: global   # На каждом сервере Swarm — один экземпляр
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:11.5.2
#    ports:
#      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SERVER_ROOT_URL: http://vpn-boriska.ru/grafana
    #      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - monitoring_net
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
      - "9095:9095"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring_net

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config.yml:/etc/promtail/config.yml:ro
      - /tmp:/tmp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm906802   # ← ЗАМЕНИТЬ
    networks:
      - monitoring_net


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - monitoring_net

volumes:
  grafana_data:
    name: grafana_vol
  prometheus_data:
    name: prometheus_data
  loki_data:
    name: loki_data

networks:
  monitoring_net:
    external: true
    name: shared_net
