events {}

stream {
    upstream socks5proxy {
        server socks5proxy:8443; # 3proxy внутри контейнера
        }

    server {
        listen 443 ssl;

        ssl_certificate /etc/letsencrypt/live/proxy-boriska.vpn-boriska.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/proxy-boriska.vpn-boriska.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        proxy_pass socks5proxy;

        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }
}
