# === General Settings ===
[general]
#ad_tag = "d7cd893d0745737f398ac95ab053fa24"
use_middle_proxy = false

[general.modes]
classic = false
secure = false
tls = true

[server]
port = 443

[server.api]
enabled = true
listen = "0.0.0.0:9091"
whitelist = ["0.0.0.0/32"]
read_only = false
#
# === Anti-Censorship & Masking ===
[censorship]
tls_domain = "petrovich.ru"

[access.users]
# format: "username" = "32_hex_chars_secret"
hello = "3568fc0a67ee1d94475104b2f42ac8aa"