name: Linters Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_vpn_boriska:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Выполняется только для ветки main.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонирование репозитория

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3  # Настройка SSH-ключа
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Приватный ключ из секретов

      - name: Add known hosts
        run: echo "${{ secrets.SERVER_IP }} $(ssh-keyscan -H ${{ secrets.SERVER_IP }})" >> ~/.ssh/known_hosts  # Добавление сервера в known_hosts
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "whoami" && echo PRIVET # Проверка подключения

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd production/monitoring || exit  # Переход в директорию приложения
          git pull origin main            # Обновление кода из репозитория
          docker compose down
          docker build -t socks5proxy:latest ./socks5_proxy
          docker stack rm monitoring
          docker stack deploy -c docker-stack.yml monitoring
          docker compose up -d --build
          EOF
  deploy_help_blocks:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Выполняется только для ветки main.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонирование репозитория

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3  # Настройка SSH-ключа
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY2 }}  # Приватный ключ из секретов

      - name: Add known hosts
        run: echo "${{ secrets.SERVER_IP2 }} $(ssh-keyscan -H ${{ secrets.SERVER_IP2 }})" >> ~/.ssh/known_hosts  # Добавление сервера в known_hosts
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER2 }}@${{ secrets.SERVER_IP2 }} "whoami" && echo PRIVET # Проверка подключения

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER2 }}@${{ secrets.SERVER_IP2 }} << 'EOF'
          cd test_zone/monitoring || exit  # Переход в директорию приложения
          git pull origin main            # Обновление кода из репозитория
          EOF